### ISSUE TITLE
New Category for Creating Workflows

### ISSUE THREAD

**Issue by derimagia** [derimagia/awesome-alfred-workflows#9]
Need to create a category for creating workflows. This includes any tools that are useful. Main ones that will probably be there are most likely updaters (Example is maybe Packal Updater and maybe the newly released http://www.alfredforum.com/topic/9224-oneupdater-%E2%80%94-update-workflows-with-a-single-node/)

@vitorgalvao @sindresorhus Since both of you have released a decent amount of workflows I would appreciate a comment if you have a second although I'm sure there isn't much here

**Comment by sindresorhus** [comment]
Sounds like a good idea. https://github.com/sindresorhus/alfy would probably fit un such a category.

**Comment by vitorgalvao** [comment]
Also sounds good to me. Libraries like [`alfred-workflow`](https://github.com/deanishe/alfred-workflow) might also fit. Probably a good idea to call the category something generic like “Helpers”.

**Comment by derimagia** [comment]
I added the initial category. @vitorgalvao I see you use a few external helpers like [terminal-notifier](https://github.com/vitorgalvao/alfred-workflows/tree/d7cd3b599b7bea058c78d431ffb7313da783e4aa/WebScreenshot/_licensed/terminal-notifier). Would you recommend this as a helper?

**Comment by vitorgalvao** [comment]
> I see you use a few external helpers like terminal-notifier. Would you recommend this as a helper?

Not really, as it’s likely more work than it’s worth for most people and I don’t see it used much (or at all) in workflows by other developers I respect and am sure know about `terminal-notifier` ([short discussion on this](http://www.alfredforum.com/topic/1233-strongpassword-—-get-a-strong-password-by-leveraging-multiple-sources/?p=25506)).

For context, the only reason I use `terminal-notifier` (and [`notificator`](https://github.com/vitorgalvao/notificator) before it) is so I can provide a notification that looks native to an app with an icon that does not need to use Alfred’s icon to be present as well. I do it so often, I’ve [made a script](https://github.com/vitorgalvao/tiny-scripts/blob/master/customise-terminal-notifier) to download `terminal-notifier` and replace its icon. Using `terminal-notifier` instead of Alfred’s default notifications is considerably more work simply for a (arguably worth it) marginally better aesthetic and experience. Being a designer, that’s important to me, but I don’t really think that adds much of value to the list. The multiple language helpers/frameworks seem something much better suited.

In sum, `terminal-notifier` is good but not really an Alfred resource, especially since to make it worth it to include, you need to make modifications to it.

**Comment by derimagia** [comment]
I'm actually a pretty big fan of the small things in workflows/apps like that. I would personally go the extra mile for it. But I see what you mean.  I would like to document it but it is a bit niche and isn't Alfred specific. There may another list it could go on but I'm not sure which one.

I'll mark this as resolved - other items for the category can be submitted in other pull requests/issues. Thanks again for your feedback!
